### ISSUE TITLE
overflow error in MultiSim.compare()

### ISSUE THREAD

**Issue by pausz** [InstituteforDiseaseModeling/covasim#310] opened 2021-04-22 07:11 UTC
**Describe the bug**

Trying to cast infinity as an int causes an `OverflowError` in `MultiSim.compare()` [[run.py; line 398](https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/run.py#L398)]. 
The infinity value was produced by a numerical overflow in in multiply  `init_nab = peak_nab * nab_boost`[[ immunity.py; line 190](https://github.com/InstituteforDiseaseModeling/covasim/blob/master/covasim/immunity.py#L190)]
which produces a runtime warning. 

**To reproduce**

https://github.com/brain-modelling-group/covasim-qld-vaccine/blob/master/qld-model/run_qld_ideal_vaccine_rollout.py

```python
import covasim as cv
import numpy as np

cv.check_version('>=3.0.0', die=True)


def vaccine_phase_subtargets_instantaneous(sim, phase_label):
    # Phase 1a is about 2.4% of the total population
    sim_pop_size = len(sim.people)

    phase1a_age_group = cv.true((sim.people.age >=25)*(sim.people.age <= 60))
    phase1a_subpop_size = int((sim_pop_size * 0.024))
    # Make an array of size pop_size
    phase1a_subpop = np.zeros((sim_pop_size, ), dtype=bool)
    # Select phase1a_pop_size agents within the age-bracket specified  
    phase1a_agents = np.random.choice(sim.people.uid[phase1a_age_group], phase1a_subpop_size, replace=False)
    phase1a_subpop[phase1a_agents] = True

    # Phase 1b is about 20.5% of the total population -- no risk of overlapping with phase 1b
    phase1b_age_group = cv.true(sim.people.age >= 70)
    phase1b_subpop_size = int((sim_pop_size * 0.205))
    phase1b_subpop = phase1b_age_group

    # Phase 2a is about 29.3% of the total population
    phase2a_age_group = cv.true((sim.people.age >= 50) * (sim.people.age < 70))
    phase2a_subpop_size_theoretical = int((sim_pop_size * 0.246))

    # Check that we don't select agents that were selected in phase 1a
    if (len(set(phase1a_agents).intersection(set(sim.people.uid[phase2a_age_group]))) == 0):
        phase2a_subpop = phase2a_age_group
    else:
        phase2a_subpop = np.zeros((sim_pop_size, ), dtype=bool)
        # Only get the indices that do not overlap
        phase2a_agents = list(set(sim.people.uid[phase2a_age_group]).difference(set(phase1a_agents)))
        phase2a_subpop[phase2a_agents] = True
        print(*["Theoretical percentage of phase2a population: ", phase2a_subpop_size_theoretical/sim_pop_size])
        print(*["Final percentage after removing overlapping agents from phase1a: ", phase2a_subpop.sum()/sim_pop_size])

   
    # Phase 2b is 29.3% of the total population
    phase2b_age_group =cv.true((sim.people.age >= 18) * (sim.people.age < 50))
    phase2b_subpop_size_theoretical = int((sim_pop_size * 0.293))

    # Check that we don't select agents that were selected in phase 1a
    if (len(set(phase1a_agents).intersection(set(sim.people.uid[phase2b_age_group]))) == 0):
        phase2b_subpop = phase2b_age_group
    else:
        phase2b_subpop = np.zeros((sim_pop_size, ), dtype=bool)
        # Only get the indices that do not overlap
        phase2b_agents = list(set(sim.people.uid[phase2b_age_group]).difference(set(phase1a_agents)))
        phase2b_subpop[phase2b_agents] = True
        print(*["Theoretical percentage of phase2b population: ", phase2b_subpop_size_theoretical/sim_pop_size])
        print(*["Final percentage after removing overlapping agents from phase1a: ", phase2b_subpop.sum()/sim_pop_size])
    
    # Phase 3 is 23% of the total population
    phase3_age_group = cv.true(sim.people.age < 18)
    phase3_subpop_size = int((sim_pop_size * 0.23))
    phase3_subpop = phase3_age_group
    
    vaccine_rollout_phases = {'phase1a': {'start_date': sim.day('2021-02-22'),
                                          'subpop_inds': phase1a_subpop,
                                          'prob': 1.0,
                                          'vaccine_brand': 'pfizer'},
                              'phase1b': {'start_date': sim.day('2021-03-22'),
                                          'subpop_inds': phase1b_subpop,
                                          'prob': 1.0,
                                          'vaccine_brand': 'az'},
                              'phase2a': {'start_date': sim.day('2021-05-17'),
                                          'subpop_inds': phase2a_subpop,
                                          'prob': 1.0,
                                          'vaccine_brand': 'az'},
                              'phase2b': {'start_date': sim.day('2021-07-26'),
                                          'subpop_inds': phase2b_subpop,
                                          'prob': 1.0,
                                          'vaccine_brand': 'az'},
                              'phase3': {'start_date': sim.day('2021-10-03'),
                                          'subpop_inds': phase3_subpop,
                                          'prob': 1.0,
                                          'vaccine_brand': 'az'} }   

    # Indices with people that fall within this age group 
    vals = np.zeros((sim_pop_size )) 
    vals[vaccine_rollout_phases[phase_label]['subpop_inds']] =  vaccine_rollout_phases[phase_label]['prob']# probability for people in this subpopulation
    subtarget_dict = dict(inds = sim.people.uid,
                          vals = vals)
    phase_start_date = vaccine_rollout_phases[phase_label]['start_date']
    vaccine_brand = vaccine_rollout_phases[phase_label]['vaccine_brand']
    
    return vaccine_brand, phase_start_date, subtarget_dict     

# start day
start_day = '2021-01-22'
end_date = '2021-12-31'

# Queensland age data - ABS September 2020
qld_age_data = {
   '0-4':  314602,
   '5-9':  339247,
  '10-14': 345205,
  '15-19': 319014,
  '20-24': 338824,
  '25-29': 370468,
  '30-34': 362541,
  '35-39': 354219,
  '40-44': 325208,
  '45-49': 348003,
  '50-54': 321168,
  '55-59': 317489,
  '60-64': 288317,
  '65-69': 254114,
  '70-74': 226033,
  '75-79': 156776,
  '80-84': 100692,
  '85-89': 57073,
  '90-94': 28134,
  '95-99': 7931,
  '100-104':1128
  }


# Update with qld population stats
cv.data.country_age_data.data['Australia'] = qld_age_data

import_dates = ['2021-01-22',
                '2021-02-22',
                '2021-03-22',
                '2021-04-22',
                '2021-05-22',
                '2021-06-22',
                '2021-07-22',
                '2021-08-22',
                '2021-09-22',
                '2021-10-22',
                '2021-11-22',
                '2021-12-22']

# Define list with imports 
imported_infections = [cv.strain('p1', days=cv.day(day, start_day=start_day), n_imports=100) for day in import_dates]


# simulation parameters
pars = {
    'pop_size': 200000,
    'pop_type': 'hybrid',
    'location': 'Australia',
    'rand_seed': 42,      # Random seed to use
    'beta': 0.0113,       # QLD calibration global beta
    'pop_infected': 0,
    'n_imports': 0,
    'n_strains': 1,
    'strains': imported_infections,
    'start_day': start_day,
    'end_day':   '2021-12-31',
    'use_waning': True}

# Baseline simulator - no interventions
sim_baseline = cv.Sim(pars)
sim_baseline.initialize()        # Initialize models


# Vaccine rllout simulation - vaccination is the only intervention
sim_vaccine = cv.Sim(pars)
sim_vaccine.initialize()  # need to intialize to generate People()

# Rollout 
vaccine_phases = ['phase1a','phase1b', 'phase2a', 'phase2b', 'phase3']
for key in vaccine_phases:
    vaccine_brand, phase_start, phase_target =  vaccine_phase_subtargets_instantaneous(sim_vaccine, key)
    sim_vaccine.pars['interventions'].append(cv.vaccinate(vaccine=vaccine_brand, days=[phase_start], prob=0.0, subtarget=phase_target))
sim_vaccine.initialize()  #need to initialize again otherwise covasim complains that the intervention has not been initialized

msim = cv.MultiSim([sim_baseline, sim_vaccine])
msim.run()

df = msim.compare(output=True)
print(df)

msim.plot_compare()
msim.plot_result('cum_infections')

```

**Expected behavior**
We probably don't want infinite in our results, so not sure this is actually a bug. Perhaps the simulation should stop if there's an infinity in some of the daily or cumulative results? 

The simulation summaries do not report infinite values of `cum_infections`, but I'm guessing there is at least a time point for which value of `cum_infections` is indeed infinity.  And that's the reason the error arises during a call to a plotting function, rather than being flagged as a problem during the simulation itself -- well, the runtime warning sort of gave away that there was something funky. 

**Platform (please complete the following information):**
**Platform:**
 - covasim version:3.0.1
 - sciris version: 1.1.1
 - OS: Debian GNU/Linux 10 (buster) - Linux 4.19.0-14-amd64/Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
 - Other platform information: 
      - Anaconda3 2019-03, 
      - conda 4.10.1
      - env with python 3.8.8, 
      - covasim installed from fork via `pip install -e`;

**Comment by cliffckerr** [comment] 2021-04-26 08:05
Thanks for catching, @pausz ! This is actually a double bug: `pop_nabs` should not have been cast to int, and there was a bug with `subtarget` that meant that it wasn't filtering out people who'd already been vaccinated, which meant that people were getting re-vaccinated every day. These are both fixed in 3.0.2.

**Comment by cliffckerr** [comment] 2021-06-29 06:27
Should be fixed now

**Closed by cliffckerr** 2021-06-29 06:27 UTC

**Comment by cliffckerr** [comment] 2021-06-29 06:28
Should be fixed, or if not, is a duplicate of https://github.com/amath-idm/covasim/issues/1016
