### ISSUE TITLE
test_prob intervention- test_delay 0 doesn't work

### ISSUE THREAD

**Issue by CWiswell-IDM** [InstituteforDiseaseModeling/covasim#176] opened 2020-04-20 23:23 UTC
If you set a test_delay of 0 (same day diagnosis) on the test prob intervention, you still don't get test results until the following timestep. 

I think this is a known issue (as it was marked as a duplicate in another repository) but I can't find the original bug report.

**Comment by ckerr-IDM** [comment] 2020-04-21 00:20
Golly darn it! I fixed this and it seems to have come back. I noticed this too in the calibration that there seems to be a 1-day delay w.r.t. the data. Can you include minimal steps to reproduce?

**Comment by CWiswell-IDM** [comment] 2020-04-21 04:17
Let's try this
```
import covasim as cv
tp_intervention = cv.test_prob(symp_prob=1.0, test_sensitivity=1.0, test_delay=0, start_day=30)
test_sim = cv.Sim()
test_sim['interventions'] = tp_intervention
test_sim.run()
```
And to see it
```
results = test_sim.to_json(tostring=False)
results = test_sim.to_json(tostring=False)
print(results['results']['n_symptomatic'][29:32])
print(results['results']['new_tests'][29:32])
print(results['results']['new_diagnoses'][29:32])
```

Hope that helps!

**Comment by ckerr-IDM** [comment] 2020-04-21 06:18
@CWiswell-IDM Are you sure this isn't fixed on develop? I ran it and I get
```

[87.0, 110.0, 120.0]
[0.0, 110.0, 18.0]
[0.0, 110.0, 18.0]
```
which seems to be right?

**Comment by CWiswell-IDM** [comment] 2020-04-21 13:17
That looks right! I'll change the unittest to use delay 0 again and run. While I'm at it, can quickly add a test of the test_delay parameter specifically

**Comment by cliffckerr** [comment] 2020-04-22 01:19
@CWiswell-IDM can you close this?

**Comment by cliffckerr** [comment] 2020-04-22 06:45
Closing since seems to be fixed

**Closed by cliffckerr** 2020-04-22 06:45 UTC
Labels: bug

**Comment by CWiswell-IDM** [comment] 2020-04-22 15:29
Whoops, sorry, should have closed this myself. Thank you!
